APT::FTPArchive::Release::Origin "traphumi";
APT::FTPArchive::Release::Label "traphumi-archive";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "traphumi official package repository";
